feat: fixes multiplicity issues, adds support for combining schemas, …
Informasjonsforvaltning/fdk-model-publisher pull request #24
Opened 2021-02-03 09:45 UTC by matsjs

…optional properties, and codeLists and codeElements

2021-02-04 08:22 UTC, NilsOveTen requested changes
Det er en del ressurser som får dobbel rdf-type. Ser ut som det er snakk om Attribute og CodeList som begge får overflødig ObjectType

2021-02-04 08:22 UTC, NilsOveTen commented on src/fdk_model_publisher/service/mapper.py
> +) -> List[ModelProperty]:
Hvorfor ikke bare returnere `Composition`? Er det noen gang noe annet?

2021-02-04 08:22 UTC, NilsOveTen commented on src/fdk_model_publisher/service/mapper.py
> +) -> List[Union[ModelElement, CodeElement]]:
Er ikke CodeElement en underklasse av ModelElement? `) -> List[ModelElement]:` går i så fall helt fint

2021-02-04 08:22 UTC, NilsOveTen commented on tests/mocks/skagerrak_sparebank_ttl.py
> +        ns2:ObjectType ;
Dobbel rdf-type, fjern en. Regner med det er ObjectType som er feil

2021-02-04 08:22 UTC, NilsOveTen commented on tests/mocks/skagerrak_sparebank_ttl.py
> +        ns2:ObjectType ;
Fjern ObjectType

2021-02-04 11:31 UTC, matsjs commented on src/fdk_model_publisher/service/mapper.py
> +) -> List[Union[ModelElement, CodeElement]]:
CodeElement er "frittstående"

2021-02-12 14:25 UTC, NilsOveTen approved these changes

2021-02-12 14:57 UTC, merged