feat: adds max and min exclusive properties
Informasjonsforvaltning/fdk-model-publisher pull request #53
Opened 2021-08-18 06:51 UTC by matsjs

2021-08-19 11:34 UTC, NilsOveTen requested changes
Ser ikke helt hva med koden som er galt, men den feiler ganske hardt i staging atm...

```
File "/app/src/fdk_model_publisher/service/fetcher.py", line 61, in fetch
    model.title = await openapi.get("title")
TypeError: object str can't be used in 'await' expression
```

2021-08-19 12:14 UTC, NilsOveTen commented
> Ser ikke helt hva med koden som er galt, men den feiler ganske hardt i staging atm...
> 
> ```
> File "/app/src/fdk_model_publisher/service/fetcher.py", line 61, in fetch
>     model.title = await openapi.get("title")
> TypeError: object str can't be used in 'await' expression
> ```

Ser dette også skjer i demo, så har vel ikke noe med denne pr'en å gjøre

2021-08-19 12:14 UTC, NilsOveTen approved these changes

2021-08-23 06:27 UTC, frederik-ronnevig approved these changes

2021-08-23 06:28 UTC, frederik-ronnevig commented
Hei @NilsOveTen det du beskriver var den feilen som jeg satt og klødde meg i hodet med. ;-) Den har @matsjs fikset i denne PR'en:

https://github.com/Informasjonsforvaltning/fdk-model-publisher/pull/54

2021-08-23 06:45 UTC, merged